#!/usr/bin/env bash
#
# Endfield Mod Loader.
# Made to work with Elysia. With everything else... Good Luck ;)
#
# First run (or `--reconfigure`) scans your home directory for Proton,
# umu, Steam Linux Runtime and Wine-prefix installs, lets you pick the
# right ones, asks for the game .exe and then remembers all of it in a 
# config file so you don't have to type paths again.

set -euo pipefail

# ===========================================================================
# Configuration & Environment Defaults
# ===========================================================================
USER_HOME="${HOME:-/home/$(whoami)}"

DEFAULT_LOADER_DIR="${USER_HOME}/Downloads/Endfield"
OLD_LOADER_DIR="${USER_HOME}/Downloads/endfield-mods"

LOADER_DIR="${LOADER_DIR:-$DEFAULT_LOADER_DIR}"
CONFIG_FILE="${LOADER_DIR}/config.conf"

# Wine / Runner settings
export STORE="umu"
export GAMEID="umu-1fe562f5ee"
export WINEDLLOVERRIDES="d3d11=n,b"

# Repositories & binary names
readonly REPO_EFMI="SpectrumQT/EFMI-Package"
readonly REPO_LIBS="SpectrumQT/XXMI-Libs-Package"
readonly PROCESS_NAME="Endfield.exe"
readonly INJECTOR_NAME="XXMI Launcher.exe" # Matches d3dx.ini default [Loader] value

TMP_DIR=""
RECONFIGURE=0

# ===========================================================================
# Logging & Cleanup Helpers
# ===========================================================================
log_info()  { printf '\033[1;34m[INFO]\033[0m %s\n'  "$*" >&2; }
log_warn()  { printf '\033[1;33m[WARN]\033[0m %s\n'  "$*" >&2; }
log_error() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; }
die()       { log_error "$*"; exit 1; }

cleanup() {
  if [[ -n "${TMP_DIR:-}" && -d "$TMP_DIR" ]]; then
    rm -rf "$TMP_DIR"
  fi
}
trap cleanup EXIT INT TERM

print_usage() {
  cat <<EOF
Usage: $(basename "$0") [--reconfigure|-r] [--help|-h]

  --reconfigure, -r   Ignore any saved configuration and re-run the
                      interactive Proton/umu/runtime/prefix/game scan.
  --help, -h          Show this help text.

Saved configuration lives at:
  ${CONFIG_FILE}
Delete that file (or pass --reconfigure) to redo setup from scratch.
EOF
}

for arg in "$@"; do
  case "$arg" in
    --reconfigure|-r) RECONFIGURE=1 ;;
    --help|-h) print_usage; exit 0 ;;
    *) die "Unknown argument: $arg (see --help)" ;;
  esac
done

check_dependencies() {
  local deps=("curl" "unzip" "awk" "find" "x86_64-w64-mingw32-gcc")

  for cmd in "${deps[@]}"; do
    command -v "$cmd" >/dev/null 2>&1 || die "Missing required dependency: '$cmd'. Please install it."
  done
}

# ===========================================================================
# Config file (cached answers)
# ===========================================================================
load_config() {
  [[ -f "$CONFIG_FILE" ]] || return 0
  log_info "Loading saved configuration from ${CONFIG_FILE}"

  local key value
  while IFS='=' read -r key value; do
    [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
    value="${value%\"}"
    value="${value#\"}"
    if [[ -z "${!key:-}" ]]; then
      printf -v "$key" '%s' "$value"
    fi
  done < <(grep -v '^[[:space:]]*#' "$CONFIG_FILE" || true)
}

save_config() {
  mkdir -p "$LOADER_DIR"
  cat > "$CONFIG_FILE" <<EOF
# Auto-generated by modding.sh on $(date -Iseconds)
# Delete this file, or run modding.sh --reconfigure, to redo setup.
WINEPREFIX="${WINEPREFIX}"
PROTONPATH="${PROTONPATH}"
RUNTIMEPATH="${RUNTIMEPATH}"
UMU_RUN="${UMU_RUN}"
GAME_EXE="${GAME_EXE}"
LOADER_DIR="${LOADER_DIR}"
EOF
  log_info "Saved configuration to ${CONFIG_FILE}"
}

# ===========================================================================
# Interactive discovery
# ===========================================================================
# Directories that are noise.
readonly -a PRUNE_DIRS=(".cache" ".git" "node_modules" ".local/share/Trash")

# Populates the nameref array passed as $1.
build_prune_expr() {
  local -n out="$1"
  local p
  out=()
  for p in "${PRUNE_DIRS[@]}"; do
    out+=(-path "*/${p}" -o)
  done
  [[ ${#out[@]} -gt 0 ]] && unset 'out[${#out[@]}-1]'
}

# Full directory tree under $USER_HOME.
ALL_DIRS=()

build_dir_cache() {
  local -a prune_expr=()
  build_prune_expr prune_expr

  mapfile -t ALL_DIRS < <(
    find "$USER_HOME" \( "${prune_expr[@]}" \) -prune -o -type d -print 2>/dev/null | sort -u
  )
  log_info "Indexed ${#ALL_DIRS[@]} directories under ${USER_HOME}."
}

# Filter ALL_DIRS whose *basename* matches any of the given patterns.
match_dirs_by_pattern() {
  local -n out="$1"; shift
  local -a patterns=("$@")
  local d name pat matched
  out=()
  shopt -s nocasematch
  for d in "${ALL_DIRS[@]}"; do
    name="${d##*/}"
    matched=0
    for pat in "${patterns[@]}"; do
      [[ "$name" == $pat ]] && { matched=1; break; }
    done
    (( matched )) && out+=("$d")
  done
  shopt -u nocasematch
}

# From ALL_DIRS, collect entries that live under one of the given parent dirs.
# At most $depth path segments deeper.
children_within_depth() {
  local -n out="$1"; local depth="$2"; shift 2
  local -a parents=("$@")
  local d p rel slash_count
  out=()
  for p in "${parents[@]}"; do
    for d in "${ALL_DIRS[@]}"; do
      case "$d" in
        "$p"/*)
          rel="${d#"$p"/}"
          slash_count="${rel//[^\/]}"
          (( ${#slash_count} < depth )) && out+=("$d")
          ;;
      esac
    done
  done
  [[ ${#out[@]} -gt 0 ]] && mapfile -t out < <(printf '%s\n' "${out[@]}" | sort -u)
}

# Any directory one-or-two levels below a directory whose *name* matches one
# of the given patterns. Depth 2 reaches e.g.
# .../steamrt/<version>/SteamLinuxRuntime_sniper in one pass.
# Multiple patterns can be given.
scan_children_of_named_dirs() {
  local target_var="$1"; local depth="$2"; shift 2
  local -a parents=()
  match_dirs_by_pattern parents "$@"
  children_within_depth "$target_var" "$depth" "${parents[@]}"
}

# Any directory with "proton" in its name, but not literally named "proton".
scan_proton_candidates() {
  local -n out="$1"
  local -a raw=()
  match_dirs_by_pattern raw "*proton*"
  local d name
  out=()
  shopt -s nocasematch
  for d in "${raw[@]}"; do
    name="${d##*/}"
    [[ "$name" == "proton" ]] && continue
    out+=("$d")
  done
  shopt -u nocasematch
}

# Present $opts for selection.
choose_option() {
  local -n result="$1"
  local prompt="$2"
  shift 2
  local opts=("$@" "Enter path manually")
  local choice=""

  echo "" >&2
  echo "$prompt" >&2

  if command -v fzf >/dev/null 2>&1; then
    choice=$(printf '%s\n' "${opts[@]}" | fzf --prompt="> " --height=60% --reverse --cycle) || true
  fi

  if [[ -z "$choice" ]]; then
    local PS3="> "
    select opt in "${opts[@]}"; do
      if [[ -n "$opt" ]]; then
        choice="$opt"
        break
      else
        echo "Invalid choice, try again." >&2
      fi
    done
  fi

  if [[ "$choice" == "Enter path manually" ]]; then
    read -rp "Path: " result
  else
    result="$choice"
  fi
}

pick_game_exe() {
  log_info "Scanning for Endfield.exe..."
  local roots=("$USER_HOME")
  [[ -d "/run/media/${USER:-}" ]] && roots+=("/run/media/${USER:-}")
  [[ -d "/mnt" ]] && roots+=("/mnt")
  [[ -d "/media" ]] && roots+=("/media")

  local -a prune_expr=()
  build_prune_expr prune_expr

  local candidates
  mapfile -t candidates < <(
    find "${roots[@]}" \( "${prune_expr[@]}" \) -prune -o -type f -iname "Endfield.exe" -print 2>/dev/null | sort -u
  )
  choose_option GAME_EXE "Select the Endfield.exe game executable:" "${candidates[@]}"
}

configure() {
  if [[ -z "${WINEPREFIX:-}" || -z "${PROTONPATH:-}" || -z "${RUNTIMEPATH:-}" || -z "${UMU_RUN:-}" ]]; then
    log_info "Scanning ${USER_HOME} for Proton, umu, runtime, and prefix installs -- this can take a moment..."
    build_dir_cache
  fi

  if [[ -z "${WINEPREFIX:-}" ]]; then
    local wp_candidates=()
    scan_children_of_named_dirs wp_candidates 1 "*wineprefix*"
    choose_option WINEPREFIX "Select your Wine prefix (WINEPREFIX):" "${wp_candidates[@]}"
  fi

  if [[ -z "${PROTONPATH:-}" ]]; then
    local proton_candidates=()
    scan_proton_candidates proton_candidates
    choose_option PROTONPATH "Select your Proton build (PROTONPATH):" "${proton_candidates[@]}"
  fi

  if [[ -z "${RUNTIMEPATH:-}" ]]; then
    local rt_candidates=()
    scan_children_of_named_dirs rt_candidates 2 "*steamrt*" "*steamlinuxruntime*" "*steam*runtime*"
    choose_option RUNTIMEPATH "Select your Steam Linux Runtime (RUNTIMEPATH):" "${rt_candidates[@]}"
  fi

  if [[ -z "${UMU_RUN:-}" ]]; then
    local umu_dirs=() umu_run_candidates=()
    scan_children_of_named_dirs umu_dirs 2 "umu" "*umu-launcher*"
    if [[ ${#umu_dirs[@]} -gt 0 ]]; then
      mapfile -t umu_run_candidates < <(
        for d in "${umu_dirs[@]}"; do
          find "$d" -maxdepth 1 -type f -iname "umu-run" 2>/dev/null
        done | sort -u
      )
    fi
    if [[ ${#umu_run_candidates[@]} -eq 0 ]]; then
      mapfile -t umu_run_candidates < <(find "$USER_HOME" -type f -iname "umu-run" 2>/dev/null | sort -u)
    fi
    choose_option UMU_RUN "Select your umu-run binary (UMU_RUN):" "${umu_run_candidates[@]}"
  fi

  if [[ -z "${GAME_EXE:-}" ]]; then
    pick_game_exe
  fi

  save_config
}

migrate_loader_dir() {
  if [[ -d "$OLD_LOADER_DIR" && ! -e "$LOADER_DIR" ]]; then
    log_info "Migrating ${OLD_LOADER_DIR} -> ${LOADER_DIR}"
    mv "$OLD_LOADER_DIR" "$LOADER_DIR"
  fi
}

# ===========================================================================
# Package Management
# ===========================================================================
fetch_latest_release_zip() {
  local repo="$1"
  local dest_dir="$2"
  local api_url="https://api.github.com/repos/${repo}/releases/latest"
  local asset_urls asset_url zip_file asset_count

  log_info "Fetching latest release metadata for ${repo}..."

  asset_urls=$(curl -fsSL "$api_url" \
    | grep -o '"browser_download_url": *"[^"]*\.zip"' \
    | sed -E 's/.*"(https[^"]+)".*/\1/') || true
  [[ -n "$asset_urls" ]] || die "Failed to locate .zip asset URL for ${repo}."

  asset_count=$(printf '%s\n' "$asset_urls" | grep -c .)
  asset_url=$(printf '%s\n' "$asset_urls" | head -n1)
  if (( asset_count > 1 )); then
    log_warn "${repo} release has ${asset_count} .zip assets -- using the first one (${asset_url##*/})."
  fi

  TMP_DIR=$(mktemp -d)
  zip_file="${TMP_DIR}/package.zip"

  log_info "Downloading ${asset_url}..."
  curl -fsSL "$asset_url" -o "$zip_file" || die "Download failed for ${repo}"

  log_info "Extracting package to ${dest_dir}..."
  unzip -oq "$zip_file" -d "$dest_dir" || die "Failed to unzip archive for ${repo}"

  rm -rf "$TMP_DIR"
  TMP_DIR=""
}

ensure_package_files() {
  mkdir -p "$LOADER_DIR"

  # Core package check
  if [[ ! -d "${LOADER_DIR}/Core" || ! -f "${LOADER_DIR}/d3dx.ini" || ! -d "${LOADER_DIR}/Mods" ]]; then
    log_warn "Missing Core package assets. Fetching EFMI..."
    fetch_latest_release_zip "$REPO_EFMI" "$LOADER_DIR"
  fi

  # DLL dependencies check
  if [[ ! -f "${LOADER_DIR}/d3d11.dll" || ! -f "${LOADER_DIR}/3dmloader.dll" || ! -f "${LOADER_DIR}/d3dcompiler_47.dll" ]]; then
    log_warn "Missing 3DMigoto libraries. Fetching XXMI Libs..."
    fetch_latest_release_zip "$REPO_LIBS" "$LOADER_DIR"
  fi

  mkdir -p "${LOADER_DIR}/Mods" "${LOADER_DIR}/ShaderFixes"
}

# ===========================================================================
# Startup Injector Binary
# ===========================================================================
compile_injector() {
  local target_path="$1"
  local src_file

  src_file=$(mktemp --suffix=.c)

  log_info "Compiling launcher injector source binary..."

  cat << 'EOF' > "$src_file"
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <wchar.h>

typedef int (*InjectFunc)(DWORD pid, LPCWSTR dllPath, int timeoutMs);

int wmain(int argc, wchar_t *argv[]) {
  setvbuf(stdout, NULL, _IONBF, 0);
  setvbuf(stderr, NULL, _IONBF, 0);

  wchar_t gamePath[MAX_PATH] = L"";
  wchar_t dllPath[MAX_PATH]  = L"d3d11.dll";

  if (argc >= 2) {
    wcscpy(gamePath, argv[1]);
  } else {
    fwprintf(stderr, L"Usage: XXMI Launcher.exe <game_exe_windows_path> [dll_path]\n");
    return 1;
  }
  if (argc >= 3) {
    wcscpy(dllPath, argv[2]);
  }

  wprintf(L"Starting %s in suspended state...\n", gamePath);
  fflush(stdout);

  STARTUPINFOW si       = { sizeof(si) };
  PROCESS_INFORMATION pi = { 0 };

  wchar_t cmdLine[MAX_PATH * 2];
  swprintf(cmdLine, MAX_PATH * 2, L"\"%s\" -force-d3d11", gamePath);

  if (!CreateProcessW(NULL, cmdLine, NULL, NULL, FALSE, CREATE_SUSPENDED, NULL, NULL, &si, &pi)) {
    fwprintf(stderr, L"Failed to launch game (error %lu)\n", GetLastError());
    fflush(stderr);
    return 1;
  }

  HMODULE lib = LoadLibraryW(L"3dmloader.dll");
  if (!lib) {
    fwprintf(stderr, L"Failed to load 3dmloader.dll (error %lu)\n", GetLastError());
    fflush(stderr);
    ResumeThread(pi.hThread);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    return 2;
  }

  InjectFunc Inject = (InjectFunc)GetProcAddress(lib, "Inject");
  if (!Inject) {
    fwprintf(stderr, L"3dmloader.dll has no Inject() export\n");
    fflush(stderr);
    ResumeThread(pi.hThread);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    FreeLibrary(lib);
    return 3;
  }

  wprintf(L"Injecting %s into PID %lu at Frame 0...\n", dllPath, pi.dwProcessId);
  fflush(stdout);

  int result = Inject(pi.dwProcessId, dllPath, 15000);
  wprintf(L"Inject() returned %d\n", result);
  fflush(stdout);

  wprintf(L"Resuming game process...\n");
  fflush(stdout);
  ResumeThread(pi.hThread);

  wprintf(L"Game running with 3DMigoto hooked from startup. Holding process open...\n");
  fflush(stdout);

  WaitForSingleObject(pi.hProcess, INFINITE);

  CloseHandle(pi.hProcess);
  CloseHandle(pi.hThread);
  FreeLibrary(lib);
  return 0;
}
EOF

  x86_64-w64-mingw32-gcc -municode -O2 -o "$target_path" "$src_file" || {
    rm -f "$src_file"
    die "Failed to compile C injector binary."
  }

  rm -f "$src_file"
  log_info "Injector binary created: ${target_path}"
}

ensure_injector_binary() {
  local injector_path="${LOADER_DIR}/${INJECTOR_NAME}"

  if [[ ! -f "$injector_path" ]]; then
    compile_injector "$injector_path"
  else
    log_info "Injector binary exists. Skipping compilation."
  fi
}

# ===========================================================================
# INI File Configuration
# ===========================================================================
ini_set() {
  local file="$1"
  local section="$2"
  local key="$3"
  local value="$4"

  if ! grep -q "^\[${section}\]" "$file" 2>/dev/null; then
    printf '\n[%s]\n%s = %s\n' "$section" "$key" "$value" >> "$file"
    return
  fi

  awk -v section="$section" -v key="$key" -v value="$value" '
    BEGIN { in_section = 0; done = 0 }
    /^\[.*\]/ {
      if (in_section && !done) { print key " = " value; done = 1 }
      in_section = ($0 == "[" section "]")
      print; next
    }
    {
      if (in_section && $0 ~ "^[ \t]*" key "[ \t]*=") {
        print key " = " value; done = 1; next
      }
      print
    }
    END { if (in_section && !done) print key " = " value }
  ' "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
}

patch_d3dx_ini() {
  local ini_path="${LOADER_DIR}/d3dx.ini"

  [[ -f "$ini_path" ]] || die "Target file not found: ${ini_path}"

  log_info "Updating d3dx.ini options..."
  ini_set "$ini_path" "Loader" "target"                   "$PROCESS_NAME"
  ini_set "$ini_path" "Loader" "loader"                   "$INJECTOR_NAME"
  ini_set "$ini_path" "Loader" "module"                   "d3d11.dll"
  ini_set "$ini_path" "System" "dll_initialization_delay" "0"
}

# ===========================================================================
# Wine Environment Bridge
# ===========================================================================
run_in_prefix() {
  "$UMU_RUN" "$@"
}

to_windows_path() {
  run_in_prefix winepath -w "$1" 2>/dev/null | tr -d '\r'
}

# ===========================================================================
# MAIN
# ===========================================================================
main() {
  check_dependencies
  migrate_loader_dir

  if [[ "$RECONFIGURE" -eq 0 ]]; then
    load_config
  else
    log_info "Reconfiguring (--reconfigure passed) -- ignoring any saved config."
  fi

  configure

  export WINEPREFIX PROTONPATH RUNTIMEPATH UMU_RUN GAME_EXE LOADER_DIR
  ensure_package_files
  ensure_injector_binary
  patch_d3dx_ini

  cd "$LOADER_DIR"

  log_info "Translating paths to Windows format..."
  local game_win_path
  local dll_win_path
  local injector_host_path

  game_win_path=$(to_windows_path "$GAME_EXE")
  dll_win_path=$(to_windows_path "${LOADER_DIR}/d3d11.dll")
  injector_host_path="${LOADER_DIR}/${INJECTOR_NAME}"

  [[ -n "$game_win_path" && -n "$dll_win_path" ]] || die "Failed to convert Linux paths via winepath."

  log_info "Launching ${PROCESS_NAME} via startup injector..."
  run_in_prefix "$injector_host_path" "$game_win_path" "$dll_win_path"
}

main